/**
 * Auto-generated by scripts/generate-creatorcross-x-candidates.mjs
 * Generated at: 2026-04-21T20:34:54.978Z
 * Source entries: 547
 * Missing official X: 266
 * Filled candidate entries: 29
 * Processed target entries: 86
 */

export const CREATORCROSS_X_CANDIDATES: Record<string, string[]> = {
  "0047": ["huwahuwakioku"],
  "0048": ["monmonmelo"],
  "0056": ["shinatomy_jp"],
  "0062": ["ranransagan4377"],
  "0063": ["azpaca0", "niwakara"],
  "0095": ["nekota_ashu"],
  "0100": ["otonamiya"],
  "0125": ["isekai_agile"],
  "0133": ["jogosound"],
  "0201": ["kanzakianna36"],
  "0268": ["rika_79797"],
  "0305": ["mokaroon"],
  "0327": ["shijin_nico", "mentoku"],
  "0350": ["erimihane"],
  "0362": ["minase_33"],
  "0369": ["dogoods3"],
  "0385": ["koi_okazawa", "koiokazawa"],
  "0401": ["a_shiba3o"],
  "0413": ["jinkouchuu792"],
  "0417": ["tanakayaplus"],
  "0427": ["sayama_chako"],
  "0439": ["hirapoyopharaoh"],
  "0441": ["idolfunch"],
  "0442": ["do_sho0430", "do_sho0"],
  "0510": ["macaron_care"],
  "0513": ["the_namuzu", "thenamuzu"],
  "0538": ["berrynaes"],
  "0558": ["ganasing8740"],
  "0566": ["iwatya_4"],
};
